# 개발 환경 설정 파일

# 카메라 설정 (개발 환경에 최적화)
camera:
  device_id: 0  # 내장 웹캠만 사용
  device_type: "auto"  # 자동 감지 (또는 백엔드 지정: avfoundation, v4l, dshow 등)
  auto_detect: false  # 자동 감지 비활성화하여 지정된 카메라만 사용
  skip_camera_scan: true  # 카메라 스캔을 건너뛰고 직접 지정된 카메라만 사용
  width: 1920  # 카메라 해상도에 맞게 설정
  height: 1080
  fps: 5  # 카메라 0의 fps에 맞게 설정
  initialization:
    retry_count: 3  # 초기화 실패 시 재시도 횟수
  advanced:
    flip_horizontal: false  # 수평 대칭 여부
    flip_vertical: false    # 수직 대칭 여부

# 프레임 처리기 설정 (개발 시 더 작은 처리 크기)
frame_processor:
  performance:
    processing_width: 320
    processing_height: 240

# 파이프라인 설정
pipeline:
  cache_size: 20  # 개발 시 작은 캐시 크기

# 저장 설정 (개발 시 작은 저장 용량)
storage:
  max_disk_usage_gb: 0.5
  cleanup_threshold_gb: 0.4

# 로깅 설정
logging:
  level: DEBUG  # 개발 환경에서는 상세 로깅
  file: logs/development.log

yolo:
  model_name: "yolov8n.pt"
  confidence_threshold: 0.25
  iou_threshold: 0.45

gemini:
  api_key_env: "GEMINI_API_KEY"
  model: "gemini-2.0-flash"
  timeout: 30

demo:
  run_benchmark: true
  save_results: true
